# Rule
monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_2b_00.1" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  },
  {
    matches = [
      { node.name = "alsa_input.pci-0000_2d_00.4.analog-stereo" }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
