# Rule
monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_2d_00.4" }
    ]
    actions = {
      update-props = {
        device.description = "Speakers"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback" }
    ]
    actions = {
      update-props = {
        node.description = "USB Microphone"
      }
    }
  }
]
