[colors.primary]
background = '#181213'
foreground = '#eddfe0'

[colors.cursor]
text = '#181213'
cursor = '#eddfe0'

[colors.vi_mode_cursor]
text = '#181213'
cursor = '#ffb1bf'

[colors.search.matches]
foreground = '#524345'
background = '#fcb973'

[colors.search.focused_match]
foreground = '#524345'
background = '#ffb1bf'

[colors.footer_bar]
foreground = '#524345'
background = '#eddfe0'

[colors.hints.start]
foreground = '#524345'
background = '#e8bbc2'

[colors.hints.end]
foreground = '#524345'
background = '#e8bbc2'

[colors.selection]
text = '#d7c1c4'
background = '#524345'


[colors.normal]
black   = '#524345'
red     = '#ffb4ab'
green   = '#ffb1bf'
yellow  = '#e8bbc2'
blue    = '#fcb973'
magenta = '#ffb1bf'
cyan    = '#e8bbc2'
white   = '#eddfe0'


[colors.bright]
black   = '#a08c8e'
red     = '#ffb4ab'
green   = '#ffb1bf'
yellow  = '#e8bbc2'
blue    = '#fcb973'
magenta = '#ffb1bf'
cyan    = '#e8bbc2'
white   = '#eddfe0'


[colors.dim]
black   = '#524345'
red     = '#ffb4ab'
green   = '#ffb1bf'
yellow  = '#e8bbc2'
blue    = '#fcb973'
magenta = '#ffb1bf'
cyan    = '#e8bbc2'
white   = '#eddfe0'
