color0 #544247
color1 #ffb4ab
color2 #ffb4ca
color3 #f4b6c7
color4 #ffba8a
color5 #ffb1c8
color6 #f4b6c7
color7 #f0dee1
color8 #a28b90
color9 #ffb4ab
color10 #ffb4ca
color11 #f4b6c7
color12 #ffba8a
color13 #ffb1c8
color14 #f4b6c7
color15 #f0dee1

cursor                #f0dee1
cursor_text_color     #1a1113
background            #1a1113
foreground            #f0dee1
selection_foreground  #dac0c6
selection_background  #544247
active_border_color   #ffb4ca
inactive_border_color #544247
url_color             #ffb4ca

active_tab_foreground   #620733
active_tab_background   #ffb4ca
inactive_tab_foreground #dac0c6
inactive_tab_background #544247
cursor_trail_color      #dac0c6
