# Module
context.modules = [
  {
    name = "libpipewire-module-loopback"
    args = {
      node.name = "fc3_loopback"
      node.description = "HiBy FC3 Loopback"

      # Capture
      capture.props = {
        media.class = "Audio/Sink"
        node.name = "fc3_isolated"
        node.description = "HiBy FC3 Loopback"
        audio.position = [ FL FR ]
      }

      # Playback
      playback.props = {
        node.target = "alsa_output.usb-HiBy_HiBy_FC3_0-00.analog-stereo"
        audio.position = [ FL FR ]
      }
    }
  }
]
