# Theme
include themes/noctalia.conf

# Window
placement_strategy center
window_padding_width 16

# Font
font_family JetBrains Mono
bold_font JetBrains Mono Bold
italic_font JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
font_size 12.0

# Behavior
confirm_os_window_close 0
